name: Print Event

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  merge_group:
    branches: [ "master" ]

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Display event details
        run: |
          echo 'ref is ${{github.ref}}'
          echo 'ref_name is ${{github.ref_name}}'
          echo 'head_ref is ${{github.head_ref}}'
          echo 'sha is ${{github.sha}}'
          echo 'job workflow sha is ${{github.job_workflow_sha}}'
          echo 'event name is ${{github.event_name}}'
          echo 'event path is ${{github.event_path}}'
          echo '::group::event content'
          cat ${{github.event_path}}
          echo '::endgroup::'

      # Runs a single command using the runners shell
      - name: Hello world
        run: |
          echo Hello, world!
          if [ "${{github.event_name}}" == "merge_group" ]; then
            sleep 180
          else
            sleep 10
          fi
          echo Bye, world!
